### ISSUE TITLE
Use Title Case on Player Page

### ISSUE THREAD

**Issue by mattatgit** [vizorvr/vizor#1036]
* don't display hyphens in file name
* capitalise username
* Title case for title

e.g.  "moon-test-one by matt" becomes "Moon Test One by Matt"

**Comment by inDigiNeous** [comment]
@mattatgit Do we want to capitalize the username ? That would mean the username kinda loses it's meaning, as it's not a real name and is used everywhere else with all lowercase letters.

**Comment by mattatgit** [comment]
I want to be able to capitalise mine, because it is being used as a display name. I don't mind not forcing everyone to have theirs capitalised, but if we're using them as display names, i want to be able to have mine capitalised, because looks sloppy & careless to enforce lowercase for something functioning as a proper noun. Certainly doesn't make it lose its meaning.

**Comment by inDigiNeous** [comment]
Ok. We can display either the username or the first name, so I guess it would make more sense to display the first name of the user here, as it is capitalized. What I meant with capitalizing losing meaning, is that if you identify the user with the username, which is all lowercase in our case, then capitalizing that changes that username.

Let's use the first name of the user instead of the username, right ?

**Comment by gmarinov** [comment]
as discussed:

 - display the user's real name if we have it (and if there's enough space)
 - if a real name is unavailable, then display the username as they have entered it upon registration (allowing e.g. MixedCaseUsername)
