### ISSUE TITLE
a way to put more keyboard shortcuts in help panel

### ISSUE THREAD

**Issue by gmarinov** [vizorvr/vizor#1165]

**Comment by esaruoho** [comment]
@gmarinov what did you have in mind? I took a look at 
**vizor/views/patch_editor/help_shortcuts.handlebars** and that seems to be fairly easy to edit. I created a PR #2012 with some tweaks to it - so all text-per-key is on the same row, instead of on multiple rows. 

Also added "Handy Keys". I think this PR can be tweaked, and I'll tweak it a bit, once I get some feedback from Lintu or someone else.

**Comment by esaruoho** [comment]
yeah so basically there's a twocol and a threecol in core.less site.less -files, but switching to threecol does not actually in any way change from two columns to three columns, unfortunately.

**Comment by esaruoho** [comment]
Closed by #2018
