### ISSUE TITLE
Private / Public switch on publish.

### ISSUE THREAD

**Issue by fthr** [vizorvr/vizor#1178]

**Comment by fthr** [comment]
We need a design for private/public switch. Some thoughts:

- This probably could live in the "publish this scene" popup modal that comes when you hit publish.

- The privately published scene should be given an URL http://vizor.io/fthr/myscene but it shouldn't be accessible unless i'm logged in as fthr. Other users will see some kind of error message "The scene you try to access is private".

- When I enter that private URL logged in as fthr, I should see it normally, but it should be visually indicated that "this scene is private, change".

- Both private and published graphs should show in my /fthr/ userpage when I'm logged in, but to other users only public ones should show.

**Comment by fthr** [comment]
Alternative idea to this: There could be two buttons - Save (private) and Publish (public).

**Comment by eric-schleicher** [comment]
Save and publish are complimentary but different actions?

From what I've observed.  In vizor, publish = commit = (meta) save. Publish
is tied to a url.

Many systems let's you control the friendly url an asset is published as as
long as it's doesn't already exist or isn't reserved.

It would be nice to save graphs and publish them with independently with
the ability to set the published name.

This way when improvement to graphs are make, the user can control what
graph is loaded when a published url is requested.

This is type of functionality is very common in e-commerce platforms and
allows SEO juice to be retained when an assets details change. Or on vizor
parlance, a fork occurs and a graph evolves.

Maybe not so critical now, but as an asset platform this may be a good
paradigm.

Save (rather than publish) is nice and with a toggle/slider for publish
with a "name" input would be great.

Maybe user's graphs list page show published settings as well.

My $.02

Can collect some examples I've seen if interested.

Eric

**Comment by gmarinov** [comment]
also #1230 #1079
