### ISSUE TITLE
boilerplate UI elements - design review

### ISSUE THREAD

**Issue by gmarinov** [vizorvr/vizor#1520]
![img_0041](https://cloud.githubusercontent.com/assets/14101296/14363417/0f9da130-fcfc-11e5-85f0-a545347a3d6e.PNG)

![img_0040](https://cloud.githubusercontent.com/assets/14101296/14363420/12b91b4c-fcfc-11e5-914c-9f4950ab655e.PNG)

**Comment by gmarinov** [comment]
I've taken the arrow out (tapping it didn't work) and made the cog a little smaller in the meantime.

**Comment by kschzt** [comment]
@gmarinov @mattatgit can close this?

**Comment by mattatgit** [comment]
@gmarinov can we take the line out ? Doesn't seem to really serve any purpose. Also could you tag me in design review tickets please, this is the first time i've seen this. So long as the arrow is gone, i'm basically ok with it, because that was kind of crazy (sitting there over all content & huge). But yeah ideally lose the line too, it's just distracting.
