### ISSUE TITLE
Objects inside an opaque object disappear when editor camera is rotated

### ISSUE THREAD

**Issue by mattatgit** [vizorvr/vizor#1874]
![transparency bug](https://cloud.githubusercontent.com/assets/6858525/18117007/50ffc15c-6f8f-11e6-9f06-dcfc2e358696.gif)

**Comment by mattatgit** [comment]
This is in Safari 9.1.2 btw

**Comment by fthr** [comment]
Could you post a link to that scene?

**Comment by fthr** [comment]
This kind of looks like the classic "transparency problem" in WebGL...

This is what A-frame's docs have to say about it:

Why aren’t my transparent images rendering correctly?

Transparency is tricky in 3D graphics. If you are having issues where transparent images in the foreground do not composite correctly over images in the background, it is probably due to underlying design of the OpenGL compositor (which WebGL is an API for). In an ideal scenario, transparency in A-Frame would “just work”, regardless of where the developer places an image in 3D space, or in which order they define the elements in markup. In the current version of A-Frame, however, it is easy to create scenarios where foreground images occlude background images. This creates confusion and unwanted visual defects. A possible workaround is to try reordering your elements defined in HTML and see if that produces more expected results.

Take a look at this example. Here we have two sets of identical transparent circles. One set is positioned front-to-back while the other is back-to-front. Notice that the circles are only transparent when positioned back-to-front (relative to the camera).

**Comment by mattatgit** [comment]
Ok, thanks, Yeah, looks like that would be the problem. Don't have a link to the scene unfortunately. After i couldn't get it to work i didn't save it. I can probably recreate it without much trouble, but if its just a known limitation & not a bug, probably not much point.
