### ISSUE TITLE
Impossible to signup!

### ISSUE THREAD

**Issue by tbalouet** [vizorvr/vizor#650]
Hey guys, tried to signup to vizor, filled the fields, it doesn't work, here's a screenshot of it, I'm using Chrome on Windows 8.1 : 
![image](https://cloud.githubusercontent.com/assets/5400381/10408306/d5ba22f8-6eae-11e5-91e0-e49b08926344.png)

**Comment by kschzt** [comment]
@tbalouet thanks for reporting! looks like the reason is that your username is already taken, but the error message clearly doesn't get all the way to the UI :( ... that's already fixed in the develop branch, hopefully we can deploy that soon! 

https://github.com/vizorvr/vizor/blob/develop/browser/scripts/account-controller.js#L108
