### ISSUE TITLE
Update tooltips with useful information

### ISSUE THREAD

**Issue by mattatgit** [vizorvr/vizor#819]
Here's the first 2 that really need attention. Will add more as i write them.
- Patch (currently called Graph)

Shortcut key: 2
A patch (purple) can contain a group of other patches, called nesting. You can nest patches to build deep functionality or just to keep your graph clean and tidy. You can edit the contents of a nested patch by clicking the pencil at top right.
- Scene

Anything connected here will appear in your Vizor scene. Click the port and drag to disconnect or select the patch and hit delete.

**Comment by esaruoho** [comment]
This seems like it's related to the written this.desc (the text that appears when you hover on top of a patch) contained within each plugin created for Patches.

So, just to clarify, here's what the Nested Patch (2, purple) currently shows:
<img width="203" alt="fullscreen_01_07_2017__11_03" src="https://user-images.githubusercontent.com/4966687/27760311-f6f84870-5e4c-11e7-89cb-6282286d1001.png">

and here's what a Scene currently shows:
<img width="112" alt="fullscreen_01_07_2017__11_04" src="https://user-images.githubusercontent.com/4966687/27760315-09dfa0f0-5e4d-11e7-9744-e44f6c3245b1.png">

If I understand correctly, you would like the popup info to change to what you suggested. I'll look into it! modifying this.desc did not seem to change anything, at least not yet. I'll see where else the text is stored.

**Comment by esaruoho** [comment]
Ok, found it. All the popup descriptions are  at

**vizor/documentation/browser/plugins**

here are tests of modifications, @mattatgit do these seem like what you were looking for?

<img width="288" alt="fullscreen_01_07_2017__11_17" src="https://user-images.githubusercontent.com/4966687/27760374-e7e65c6c-5e4e-11e7-89d5-8a9cfb3c8e4b.png">

<img width="270" alt="fullscreen_01_07_2017__11_19" src="https://user-images.githubusercontent.com/4966687/27760386-20b42038-5e4f-11e7-8ab6-7342d27a171f.png">

**Comment by esaruoho** [comment]
PR posted at #2013

**Comment by mattatgit** [comment]
@esaruoho yeah, basically. Could be a bit shorter probably, and the shortcut key text should come after the explanation & be formatted differently to the body copy.

eg:  

A Nested Patch can contain other patches. Nest patches to build complex functions or just to tidy things up. Click the pencil icon to edit.   
Keyboard shortcut `2`

**Comment by esaruoho** [comment]
@mattatgit   How's this then?
<img width="255" alt="fullscreen_01_07_2017__12_57" src="https://user-images.githubusercontent.com/4966687/27761008-f1a45c00-5e5c-11e7-95c1-9e289f308a3d.png">

**Comment by mattatgit** [comment]
Better for sure. Ideally there'd be code styled text for the shortcut key numbers eg: `2` or `1~9` rather than just *bold for the entire phrase*. But perhaps we don't have that style set up.

**Comment by esaruoho** [comment]
![27838866-fced76c8-60f5-11e7-8544-726a7a38b59e](https://user-images.githubusercontent.com/4966687/27899774-482694d2-6234-11e7-9d61-742b39244993.png)

while the look and feel of the keyboard shortcut thing has been updated, and should be closer to what @mattatgit wanted, it feels like this ticket probably can't be closed due to there being so many different atoms in the Patches app that need to be re-written. I think what we could do, is close this ticket for now and create a larger ticket with all the atoms that need to have their descriptions re-written. And eventually do that. If it's broken down to pieces (I could generate a check-list of all the patches and their writeups), it'll be easier to push interim fixes, rather than trying to fix 600+ atoms at a time.
